server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#spring:
#  application:
#    name: registry-service
#  cloud:
#    config:
#      uri: http://localhost:8081
#      username: root
#      password: s3cr3t